vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        pictures:
            uri_prefix: /img/pictures
            upload_destination: '%kernel.project_dir%/public/img/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true